# Generated by Django 5.1.6 on 2025-02-20 22:19

import django.db.models.deletion
import django.utils.timezone
import polytechnicien.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polytechnicien', '0002_member_bio_member_city_member_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.FileField(null=True, upload_to=polytechnicien.models.upload_picture),
        ),
        migrations.CreateModel(
            name='CertificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_number', models.CharField(max_length=50, null=True, unique=True)),
                ('cv', models.FileField(upload_to='certifications/cv/')),
                ('diploma', models.FileField(upload_to='certifications/diplomas/')),
                ('motivation_letter', models.FileField(upload_to='certifications/letters/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polytechnicien.member')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='courses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polytechnicien.member')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polytechnicien.member')),
            ],
        ),
    ]
